# Generated by Django 3.0.8 on 2020-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_remove_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
