# Generated by Django 3.0.8 on 2020-08-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20200813_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='desc',
            new_name='notes',
        ),
    ]
